apiVersion: v1
kind: Pod

metadata:
  name: ajith-pod

spec:
  containers:

  - name: vegetable-container
    image: dalalappagariajithkumar/vegetable-app:latest
    ports:
    - containerPort: 3000

  - name: fitness-container
    image: dalalappagariajithkumar/fitness-app:latest
    ports:
    - containerPort: 5000